# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY server/package.json server/package-lock.json ./
RUN npm install --production --ignore-scripts

# Install build tools
RUN npm install typescript --no-save

# Copy source and patch port usage
COPY server/tsconfig.json ./tsconfig.json
COPY server/src ./src
# Patch index.ts to use env PORT
RUN sed -i "s/const PORT = 3000;/const PORT = parseInt(process.env.PORT || '3000', 10);/" src/index.ts

# Build project
RUN npm run build

EXPOSE 3000
CMD ["node", "build/index.js"]
